spring:
  config:
    import: optional:configserver:http://localhost:8888/
  application:
    name: auth-service
  cloud:
    config:
      token: roottoken
  data:
    mongodb:
      host: localhost
      port: 27018