spring:
  config:
    import: optional:configserver:http://localhost:8888/
  application:
    name: project-service
  cloud:
    config:
      token: roottoken
  data:
    mongodb:
      uri: mongodb+srv://test:test@cluster0.i97k8.mongodb.net/?retryWrites=true&w=majority
      database: Cluster0